### ISSUE TITLE
Incorrect parsing of the boundary delimiter

### ISSUE THREAD

**Issue by misogohan** [staktrace/mailparse#100]
In RFC 2046, defined as
> The boundary delimiter MUST occur at the beginning of a line, i.e., following a CRLF, and the initial CRLF is considered to be attached to the boundary delimiter line rather than part of the preceding part.

However, the corresponding code is not so implemented:
https://github.com/staktrace/mailparse/blob/8b3e1adf4415d73d24e7f7367317be4eac5256b4/src/lib.rs#L866-L867

This is fatal when two boundaries like this example are given.
```
Content-Type: multipart/mixed; boundary="section_boundary"
Content-Transfer-Encoding: 7bit

--section_boundary
Content-Type: multipart/alternative; boundary="--section_boundary"
Content-Transfer-Encoding: 7bit

----section_boundary
Content-Type: text/html;
Content-Transfer-Encoding: 7bit

<em>Good evening!</em>
----section_boundary
Content-Type: text/plain;
Content-Transfer-Encoding: 7bit

Good evening!
----section_boundary
--section_boundary
```
`--section_boundary` and `----section_boundary` must be distinguished from each other, but `parse_mail` does not parse correctly.

-- But, is it real case?
I recieved such an email. 😂😐

**Comment by staktrace** [comment]
RFC 2046 also says this:

```
The boundary
   delimiter MUST NOT appear inside any of the encapsulated parts, on a
   line by itself or as the prefix of any line.  This implies that it is
   crucial that the composing agent be able to choose and specify a
   unique boundary parameter value that does not contain the boundary
   parameter value of an enclosing multipart as a prefix.
```

So the email you have is in clear violation of the spec

**Comment by misogohan** [comment]
Oh, I over looked it. Indeed, the email is wrong, and I should tell so to the sender.

On the other hand, it is practically parsable if the code is written to search for the boundary as a line.
So, I wonder if you did not mind changing the code like that. Plus, To implement so is not violation of the spec, I guess.

**Comment by staktrace** [comment]
Yeah I think it is something I should handle in `mailparse` since it occurs in the wild, but it would be good to report as a bug to the composer tool as well.
