### ISSUE TITLE
Encrypted and signed multiparts

### ISSUE THREAD

**Issue by soywod** [staktrace/mailparse#112]
With the parts iterator (#108) we can now iterate over subparts of a parsed mail. But there is a problem with `multipart/encrypted` and `multipart/signed` parts: indeed, once decrypted (or verified), an encrypted (or signed) part can contain new subparts that are missed by the iterator. It could be really nice to pass a "decrypter", this way every time the iterator meets an encrypted or signed part it pushes new subparts to itself. At the same time I find this option a bit out of the scope of your library (maybe I am wrong?).

I tried to wrap your iterator with a custom one but I have big issues with ownership (indeed, I cannot `mailparse::parse_mail` on the fly, data does not live long enough).

How would you fix this issue?

**Comment by staktrace** [comment]
Hm it does feel a bit out of scope since this lib doesn't handle decryption anywhere else. I'd be interested to see your wrapped iterator, maybe there are changes I can make in the lib to help with the ownership problems.

**Comment by soywod** [comment]
I tried something like this:

```rust
fn tpl_builder_from_parsed(parsed: &ParsedMail<'_>) -> Result<TplBuilder> {
    let mut tpl = TplBuilder::default();

    for header in &parsed.headers {
        tpl = tpl.set_header(header.get_key(), header.get_value());
    }

    let mut parts_iter = parsed.parts();

    for part in parts_iter {
        match part.ctype.mimetype.as_str() {
            "multipart/encrypted" => {
                let encrypted_body = part.get_body_raw().unwrap();
                let decrypted_part =
                    process::pipe("gpg --decrypt --quiet", &encrypted_body).unwrap();
                let parsed = mailparse::parse_mail(&decrypted_part).unwrap();
                parts_iter.chain(parsed.parts());
            }
            mime => {
                tpl = tpl.part(mime, part.get_body_raw().map_err(Error::ParseEmailError)?);
            }
        }
    }

    Ok(tpl)
}
```

**Comment by staktrace** [comment]
Yeah this is a bit tricky. I spent some time playing around with this, trying to make a single iterator that can iterate through everything but I couldn't figure out a solution. Primarily the problem is that decrypting the message gives you an owned string with a different lifetime and that fundamentally cannot live in an iterator with objects from the root iterator.

**Comment by soywod** [comment]
> Yeah this is a bit tricky.

That's why I contacted you :smile: 

> I spent some time playing around with this

Thank you for your time :pray: 

> but I couldn't figure out a solution. Primarily the problem is that decrypting the message gives you an owned string with a different lifetime and that fundamentally cannot live in an iterator with objects from the root iterator.

Yep, I came up more or less to the same conclusion :slightly_frowning_face:.

Is there a way to have a owned version of a `ParsedMail`? I saw your [example](https://github.com/staktrace/mailparse/blob/master/examples/owned.rs) but I do not see how to apply to this case.

**Comment by staktrace** [comment]
The owned version might be helpful here, but I ended up modifying your example to make it recursive which seems to work (at least it compiles, and probably will do the right thing). I don't know what your `TplBuilder` actually looks like and I don't have an example encrypted mail handy so I just stubbed out those bits, but here's my compiling version:

```rust
extern crate mailparse;

use mailparse::{parse_mail, ParsedMail};

#[derive(Default)]
struct TplBuilder {
}

impl TplBuilder {
    fn set_header(self, _key: String, _value: String) -> Self {
        self // stub
    }

    fn part(self, _mime: &str, _body: Vec<u8>) -> Self {
        self // stub
    }
}

fn to_tpl_builder(parsed: &ParsedMail<'_>) -> TplBuilder {
    walk_parts(TplBuilder::default(), parsed, true)
}

fn walk_parts(mut tpl: TplBuilder, parsed: &ParsedMail<'_>, headers: bool) -> TplBuilder {
    if headers {
        for header in &parsed.headers {
            tpl = tpl.set_header(header.get_key(), header.get_value());
        }
    }

    let parts_iter = parsed.parts();

    for part in parts_iter {
        match part.ctype.mimetype.as_str() {
            "multipart/encrypted" => {
                let encrypted_body = part.get_body_raw().unwrap();
                let decrypted_part = encrypted_body.to_vec(); //stub for process::pipe("gpg --decrypt --quiet", &encrypted_body).unwrap();
                let parsed = parse_mail(&decrypted_part).unwrap();
                tpl = walk_parts(tpl, &parsed, false);
            }
            mime => {
                tpl = tpl.part(mime, part.get_body_raw().unwrap());
            }
        }
    }

    tpl
}

fn main() {
    let data = b"Key: value\r\n\r\nSome body stuffs".to_vec();
    let mail = parse_mail(&data).unwrap();
    let _tpl = to_tpl_builder(&mail);
}
```

**Comment by soywod** [comment]
I wanted to avoid recursion but I think I have no choice there. I tried your solution and it works as expected. Thank you for the time you spent on it :pray: I guess we can close the issue.
