### ISSUE TITLE
Parsed email header with forbidden characters returned without quotes

### ISSUE THREAD

**Issue by edevil** [staktrace/mailparse#117]
If you use `parse_header()` on `b"From: =?UTF-8?B?THVpcyBHb256w6FsZXogW1ZhdXhvb10=?= <notifications@github.com>"`, and then obtain the value of said header you obtain:

`Luis González [Vauxoo] <notifications@github.com>`

However, I think that since the name contains square-brackets it should be enclosed in quotes. `mailparse` can parse the header back, but some libraries such as https://www.npmjs.com/package/email-addresses complain about this, and it seems they are correct.

**Comment by staktrace** [comment]
`parse_header` is a generic header parsing function and not specific to address headers. So it's not going to be modifying the content beyond doing the decoding of (in this case) base64 content. If there's quotes missing here it's because the sender didn't put them in.

**Comment by staktrace** [comment]
Closing for now but feel free to respond and try to change my mind :)

**Comment by wathiede** [comment]
Did you come up with a solution? I just stumbled across this too trying to use [addrparse][1]. I think it's not actually `parse_header` that does the decoding, it is [get_value][4].

So you can potentially use [get_value_raw][3], then call `String::from_utf8` on the result, pass that into [addrparse][1] then use another library to decode the quoted printable version of the structured output.

That solution isn't great though, as `get_value` also does whitespace normalization and handles multiline headers.  It seems like `addrparse` (or maybe [addrparse_header][2] given it avoids the explicit `get_value` call) would be more robust if it was possible to perform the tokenization on the endcoded form of the header, and then decode the name portion after tokenization.

[1]: https://docs.rs/mailparse/0.14.0/mailparse/fn.addrparse.html
[2]: https://docs.rs/mailparse/0.14.0/mailparse/fn.addrparse_header.html
[3]: https://docs.rs/mailparse/0.14.0/mailparse/struct.MailHeader.html#method.get_value_raw
[4]: https://docs.rs/mailparse/0.14.0/mailparse/struct.MailHeader.html#method.get_value
