### ISSUE TITLE
Doctest failure for parse_mail() 

### ISSUE THREAD

**Issue by jelmer** [staktrace/mailparse#119]
I'm getting a doctest failure running the tests in master and 0.14. It looks like mailparse returns a trailing "\r\n" but the test doesn't expect that. I'm not entirely sure which of the two is correct?

```
test src/lib.rs - parse_mail (line 900) ... FAILED

failures:

---- src/lib.rs - parse_mail (line 900) stdout ----
Test executable failed (exit status: 101).

stderr:
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `"This is the plaintext version, in utf-8. Proof by Euro: €\r\n"`,
 right: `"This is the plaintext version, in utf-8. Proof by Euro: €"`', src/lib.rs:27:5
test result: FAILED. 24 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 2.77s

error: doctest failed, to rerun pass `--doc`
```

**Comment by staktrace** [comment]
Indeed, I can reproduce this as well. I'm surprised that my CI checks didn't catch this before. It appears to have been broken since 30bef79884b775728d7d639b7852fca710ff0a92.

**Comment by staktrace** [comment]
Actually that's wrong. The quoted-printable dependency picks the latest from the 0.4.x series when running, and it was the change in 9c0e87912bb9d8df1e0c24965b9bf522eef17176 in quoted-printable that introduced the change in behaviour.
