### ISSUE TITLE
Documentation test is broken since quoted_printable 0.4.7

### ISSUE THREAD

**Issue by link2xt** [staktrace/mailparse#122]
If I use `quoted_printable = "=0.4.6"` in Cargo.toml, all tests pass.

If I set `quoted_printable = "=0.4.7"` in Cargo.toml, one of the doc tests fails:
```
---- src/lib.rs - parse_mail (line 906) stdout ----
Test executable failed (exit status: 101).

stderr:
thread 'main' panicked at src/lib.rs:28:5:
assertion `left == right` failed
  left: "This is the plaintext version, in utf-8. Proof by Euro: €\r\n"
 right: "This is the plaintext version, in utf-8. Proof by Euro: €"
stack backtrace:
...
```

This is broken by the change https://github.com/staktrace/quoted-printable/pull/16 it seems.

**Comment by staktrace** [comment]
When I check out the master branch of `mailparse`, it has quoted-printable at version 0.4.8 and `cargo tests --all` and `cargo test --doc` both pass. What am I missing? And why does your PR use 0.4.6 as the base version that's being updated?

**Comment by staktrace** [comment]
Oh I see. I think you're using the latest tagged version rather than the master branch. This issue is a dup of https://github.com/staktrace/mailparse/issues/119 and has already been fixed. Maybe you just need me to tag a new release of mailparse?

**Comment by staktrace** [comment]
I publised v0.14.1 of mailparse with the updated quoted-printable dependency.
