### ISSUE TITLE
Unexpected result from decoding Base64 encoded subparts

### ISSUE THREAD

**Issue by sanmai-NL** [staktrace/mailparse#15]
Take [this test e-mail](https://gist.github.com/billsinc/967795#file-test-email-from-phpclasses).

[`logo.gif`, as saved from Mozilla Thunderbird MUA](https://user-images.githubusercontent.com/3374183/33809419-e1094206-ddf6-11e7-995f-028682d36ace.gif)

[`logo.gif`, as extracted using `mailparse`](https://user-images.githubusercontent.com/3374183/33809423-f21c3576-ddf6-11e7-8455-69e78ca8945b.gif)

This code was used to extract `logo.gif`:
```rust
let body = subpart.get_body().unwrap().as_bytes();
```

There is corruption in the latter `logo.gif`.

Can you reproduce this?  Regardless, it should be helpful to add an integration test with this sample e-mail message as fixture.

**Comment by staktrace** [comment]
`get_body()` is intended for stuff that is convertible to a string. For binary data like a gif, you should use `get_body_raw()` instead. I verified that if I do this:

```
let body = subpart.get_body_raw().unwrap();
```

instead I get the correct result. Using `get_body()` will round-trip the data through a UTF-8 conversion or something, which is what corrupts it.
