### ISSUE TITLE
Upgrade base64 for security reasons

### ISSUE THREAD

**Issue by tirkarthi** [staktrace/mailparse#18]
Hi,

It seems this library uses a version of the library base64 which is vulnerable to security issues. Please refer to https://github.com/RustSec/advisory-db/blob/master/Advisories.toml#L53 .

patch commit : https://github.com/alicemaz/rust-base64/commit/24ead980daf11ba563e4fb2516187a56a71ad319
patched version : [">= 0.5.2"]
used version : base64 = "0.1.1"

We have found 3 modules using your module as a direct dependency : 

* maildir
* fapt-pkg
* buzz

This is done using crates.io data. Feel free to close this issue if it's not relevant.

Thanks

**Comment by staktrace** [comment]
Thanks for filing the issue! I have fixed this and published v0.6.1 of mailparse with the fix.

**Comment by tirkarthi** [comment]
You're welcome. Please consider adding [cargo-audit](https://github.com/RustSec/cargo-audit) to the CI to get notified in the future.

Thanks
