### ISSUE TITLE
Typed mimetype

### ISSUE THREAD

**Issue by vbrandl** [staktrace/mailparse#20]
I think it would be good to have the `mimetype` field in `ParsedContentType` properly typed (instead of a string). Often used types should be encoded as static variants of an enum and for everything else there can be a `Custom(&str)` variant.
I guess matching over content types of subparts might be a pretty common exercise and encoding this in the type system helps catching mistakes due to typos.

**Comment by staktrace** [comment]
Looks like there is a mime crate on crates.io that encapsulates that functionality. It should be easy for your calling code to use that crate to parse and match the mimetype.
