### ISSUE TITLE
`parse_content_disposition` should be fallible rather than default

### ISSUE THREAD

**Issue by sanmai-NL** [staktrace/mailparse#23]
When parsing many e-mail headers using `parse_content_disposition`, only a small fraction will be `Content-Disposition`. If the header is not `Content-Disposition` or malformed, a default `ParsedContentDisposition` with field `disposition` `Inline` will be constructed as a fallback. This turns out to be costly, certainly since `ParsedContentDisposition`'s `params` field is a `BTreeMap<String, String>`, which will be needlessly constructed every time. 

Can we instead make `parse_content_disposition` fallible and let API consumers use `ParsedContentDisposition`’s `Default` implementation, so that the current fallback can be used optionally when `parse_content_disposition` fails?

**Comment by sanmai-NL** [comment]
It could be helpful to leverage https://github.com/Geal/nom in order to parse efficiently while keeping the ability to handle errors, without writing a lot of extra code.

**Comment by staktrace** [comment]
If they are not a `Content-Disposition` header, why are you parsing them using `parse_content_disposition`? You should be able to fish out just the `Content-Disposition` headers using the methods on the `MailHeaderMap` trait and just pass those to `parse_content_disposition`.

**Comment by sanmai-NL** [comment]
That means every library consumer does the work of figuring out what type the header is and then calling the appropriate parser function. I suggest this is implemented in the library instead. 

A different case I mentioned is that `Content-Disposition` header can have a malformed value. Any such parser function will have to be fallible anyway.

**Comment by staktrace** [comment]
Sorry, I don't understand your use case here. Can you provide more context around what you're trying to do with the library? I can't think of a usage pattern where you would want to call `parse_content_disposition` on a header that is not actually `Content-Disposition`.

In the case of a malformed value, yes, it will return the fallback now, which incurs a needless cost, but that situation should be pretty rare. If you have a corpus of real-world email with a very high ratio of malformed `Content-Disposition` headers then I would rather modify the parser to parse those successfully.

**Comment by staktrace** [comment]
Closing for now, we can discuss if further if you are able to provide more context.
