### ISSUE TITLE
Fail on `Content-Disposition` header values that aren’t ASCII

### ISSUE THREAD

**Issue by sanmai-NL** [staktrace/mailparse#24]
See https://tools.ietf.org/html/rfc2045, https://tools.ietf.org/html/rfc2045 and https://tools.ietf.org/html/rfc6266#appendix-C.

Ideally the full grammar should be obeyed, rejecting control characters too.

**Comment by staktrace** [comment]
Can you provide a testcase that you believe is being treated incorrectly?

**Comment by staktrace** [comment]
Also note that in general the library errs on the side of graceful handling rather than hard failures, so if by "fail" you mean return an Err on cases that get encountered in real-world situations, then I'm not likely to implement that. But again, I'd like to see examples to get a better sense of what the problem is.

**Comment by sanmai-NL** [comment]
Just any header value with non-ASCII..

How do you see that, handling an invalid header value gracefully? Returning and `Error`, i.e. failing, gives the API consumer no less opportunity to handle the error in some graceful way.

**Comment by droundy** [comment]
To my thinking, handling an error gracefully means that if an email has some incorrectness in it, I'd like to see it parsed as much as possible, eg ignoring invalid headers so I can at least see the email contents. Returning an Err isn't graceful in that it requires a user who wants to see the contents of the faulty email to implement their own email parser.

**Comment by staktrace** [comment]
Agreed.

**Comment by sanmai-NL** [comment]
I see you’re asking for a test case for an obvious defect, at the same time disagreeing it’s a defect, casting doubt on whether my work will be fruitful in the first place. Also in the case of other issues I filed here.
 
Returning an error says nothing about what kind of data is accessible for further processing, be it the invalid header value as a string or bytes or whatever. The conclusion that the API consumer would need to implement their own parsers does not follow. Silently ignoring errors is never a good solution.

**Comment by staktrace** [comment]
> I see you’re asking for a test case for an obvious and simple defect, at the same time disagreeing it’s a defect, casting doubt on whether my work will be fruitful in the first place.

Yes, most likely providing a test case will not actually change my mind on this.

> Also in the case of other issues I filed here.

The other issue (#23) is different. There, I'm not asking for a testcase, just a more detailed description of how your code is structured to better understand your usecase.

> Returning an error says nothing about what kind of data is accessible for further processing, be it the invalid header value as a string or bytes or whatever. The conclusion that the API consumer would need to implement their own parser does not follow. Silently ignoring errors is never a good solution.

Never say never :) It's a tradeoff either way, and in the case of this library the choice is explicitly to allow leniency in parsing errors. I state as much in the README. If this doesn't meet your requirements, feel free to use another library or fork mine.
