### ISSUE TITLE
Address parsing support (RFC 5322 3.4)

### ISSUE THREAD

**Issue by theduke** [staktrace/mailparse#34]
It would be great if mailparse contained a function for parsing address specifications. ([RFC 5322 3.4](https://tools.ietf.org/html/rfc5322#section-3.4)).

Something like:

```rust

fn parse_address(raw: &[u8]) -> Result<Vec<Address>, AddressParseError>;

struct Address {
   pub display_name: Option<String>,
   pub address: String,
}
```

```

**Comment by staktrace** [comment]
That sounds like a good idea. I'll try to find some time to implement this, but PRs are welcome.

**Comment by theduke** [comment]
The `email-format` crate contains very extensive parsing and AST-like definitions in general, including mailbox/address information.

Might be worth checking that out.

**Comment by eaon** [comment]
Shameless self-promotion, I made this: https://crates.io/crates/email-address-list and am currently using it in conjunction with mailparse. Though given its API and dependency on Pest, I doubt it would fit into the codebase of mailparse directly.

**Comment by theduke** [comment]
Just a heads up: `email-format` panics all over the place, definitely not recommended!

@eaon  your crate seems to work fine on real world data, so :+1: .

**Comment by staktrace** [comment]
Some guidelines if anybody wants to try a PR before I get around to implementing it: I would like this code to live in a new module, `addrparse.rs` (similar to `dateparse.rs`) and have zero external crate dependencies. Keeping the crate dependency graph small is something I actively strive for.
