### ISSUE TITLE
Body contains newline separators

### ISSUE THREAD

**Issue by theduke** [staktrace/mailparse#35]
The body of subparts (and probably the main body for non-mulitpart mails) will contain the end marker of the email ( `\r\n\r\n` ), which , to my knowledge,should no be considered part of the body but just recognized as the "email is complete" marker.

**Comment by staktrace** [comment]
@theduke ^

**Comment by theduke** [comment]
I'm just fetching a mail with: `UUID FETCH XXX BODY.PEEK[]`with [imap](https://docs.rs/imap).

But I'm guessing that https://docs.rs/imap/0.10.0/imap/struct.Session.html#method.run_command_and_read_response just doesn't strip the final terminator for you and you have to do it yourself. (It also doesn't strip the initial status line, which I'm doing manually).
