### ISSUE TITLE
dateparse as a separate crate?

### ISSUE THREAD

**Issue by FauxFaux** [staktrace/mailparse#37]
The date parser in `mailparse` is very useful, much more so than the one in `chrono`, which can't read reasonable (but *technically* not standard complaint) dates, let alone realistic ones.

Would you be interested in maintaining it as a separate crate, so I can use it without depending on `mailparse`? Or, would you be happy with me forking your implementation to a new crate? Same license, or the Rust standard `MIT OR Apache2`?

**Comment by staktrace** [comment]
Feel free to fork it to a new crate with whatever license you want. At the moment there's no value for me to maintain it as a separate crate, so I'd rather not. Thanks!
