### ISSUE TITLE
How to get the mail body untouched

### ISSUE THREAD

**Issue by ufoscout** [staktrace/mailparse#38]
When the body is encoded in base64, the get_body_raw() method decodes it before it is the returned.
Is there a way to get the untouched body instead?
I need to forward to another system an attachment encoded in base64, at the moment the only way to achieve it is to call the get_body_raw() and then encode the result in base64; anyway, both the decode and the following encode actions are expensive and completely useless.

**Comment by staktrace** [comment]
No there isn't. Note that the body may be encoded using something other than base64, in that case you'd have to re-encode to base64 anyway. And even if it is base64, doing the decode and re-encode will make sure that the body is actually valid base64, and that you're not accidentally passing garbage to your downstream consumer.

**Comment by staktrace** [comment]
Closing for now. If you have additional concerns feel free to comment.

**Comment by ufoscout** [comment]
@staktrace 

> Note that the body may be encoded using something other than base64, in that case you'd have to re-encode to base64 anyway.

True, in fact, in an idiomatic rust API, I would expect a method that returns an Enum (e.g. AttachementBody::Base64, AttachementBody::Binary, etc...) that wraps something that permits me to handle the specific attachment type.

> And even if it is base64, doing the decode and re-encode will make sure that the body is actually valid base64, and that you're not accidentally passing garbage to your downstream consumer.

This does not apply to every use case. For example, in a node of a pipelined system, I only need to extract the attachment and send it to the next node in base64; I don't care if the attachment is not valid, I simply need to forward it, so I have two issues:
1. I pay for two useless decode and (re)encode steps
2. If the attachment is not valid, I get an error from the forced base64 decode step and I cannot access the attachment body; this is a big problem because I __must__ forward the attachment to the next node in any case.

**Comment by staktrace** [comment]
Still feels a bit like a layering violation to me to be exposing the transfer encoding, but there's no real harm in it I guess. The API you suggested sounds reasonable, if you make a PR with the change I can review.

**Comment by ufoscout** [comment]
@staktrace I am on it

**Comment by staktrace** [comment]
This is fixed now by your patch from #39 which I pushed. Thanks!

**Comment by ufoscout** [comment]
@staktrace 
thanks! Will you perform a new release?

**Comment by staktrace** [comment]
@ufoscout Published 0.8.0 with the changes.
