### ISSUE TITLE
Feature Request: Implement Clone, PartialEq  and Eq for ParsedMail

### ISSUE THREAD

**Issue by dignifiedquire** [staktrace/mailparse#47]
It would be great if these could be added

**Comment by staktrace** [comment]
I'm not sure how the semantics of clone would work given how the lifetime of ParsedMail is defined. It holds references into the [u8] that it was created from and I'm not sure how that would interact with cloning. You're welcome to submit a PR if it's simple. If it's complicated I'd like to better understand your use case to see if there's a better way to accomplish what you're trying to do.

**Comment by dignifiedquire** [comment]
I created #48 which solves all my issues.

**Comment by staktrace** [comment]
Closing this for now (see discussion on #48). We can reopen this if further discussion is warranted, or there are more concrete use cases that dictate what the "correct" answer here is.
