### ISSUE TITLE
Failure to parse RFC2047 encoded display-names in email addresses

### ISSUE THREAD

**Issue by hpk42** [staktrace/mailparse#50]
i am passing `=?utf-8?q?=C3=A4_space?= <x@y.org>` to `mailparse::addrparse` but it doesn't parse me out the "ä space" display name. The displayname is valid RFC2047-encoding as far as i can tell.  See https://tools.ietf.org/html/rfc2047#section-8 for examples that mirror what i am trying to do.

**Comment by staktrace** [comment]
The quoted-printable encoding is decoded by `parse_mail`. If you use `parse_mail` to get the header value it should decode that and then you can use `addrparse` on the decoded value. The behaviour you're describing is expected.

**Comment by hpk42** [comment]
ah thanks for the clarification! i found no mention of "rfc2047" in the repo -- might be useful if you mention it in the README or so (the fact that mailparser does support it, apparently).

**Comment by messense** [comment]
In https://github.com/PyO3/maturin/issues/612 a user reported a similar issue, the author field's value isn't always an address, I wonder how to parse it correctly?

**Comment by messense** [comment]
> It kind of looks like you're passing in utf-8 or other non-ascii data into `mailparse` (from [here](https://github.com/PyO3/python-pkginfo-rs/blob/17523fac9af6c50080f9e087b9fd271c49bd2ec8/src/metadata.rs#L170)) and then expecting that to not get mangled. But really you're using `mailparse` in a way that it's not meant to be used.

Do you mean that currently `mailparse` only supports ascii input?

The `build-0.4.0.tar.gz` was downloaded from https://pypi.org/project/build/0.4.0/#files which contains a `PKG-INFO` file with unicode characters in it.

**Comment by messense** [comment]
Just for comparison, the email module of Python standard library works for me:

```python
In [1]: from email.parser import Parser

In [2]: p = Parser()

In [3]: msg = p.parsestr("Author: Filipe Laíns", True)

In [4]: msg.get('Author')
Out[4]: 'Filipe Laíns'
```

**Comment by staktrace** [comment]
I don't know if there's any kind of spec for PKG-INFO files but you might be able to get away with a really simple parser that just splits on lines and then splits lines at the first colon. If your input is already utf-8 encoded then you likely don't need to handle things like quoted-printable decoding and such so simple string parsing should be good enough.

**Comment by messense** [comment]
There is a Python core metadata spec: https://packaging.python.org/specifications/core-metadata/

**Comment by staktrace** [comment]
That spec is pretty underwhelming :) it basically says "the spec is the implementation of the Python parser" so by definition there's only one compliant implementation.
