### ISSUE TITLE
Add functions to parse message IDs

### ISSUE THREAD

**Issue by link2xt** [staktrace/mailparse#53]
Parsing headers such as `Reply-To` is tricky because they are list of message IDs, and each `msg-id` may be surrounded by comments [according to RFC 5322](https://tools.ietf.org/html/rfc5322#section-3.2.2).

Since the library has address-parsing functions (#34), it would be nice to also parse message IDs.

**Comment by staktrace** [comment]
Keep in mind that the address parsing doesn't fully handle comments either. In practice they are pretty rare. I'll keep this open since it seems like a useful thing to add eventually but in almost all cases you should be fine to just split by commas to get the list of message ids.

**Comment by staktrace** [comment]
Btw, @link2xt did you actually run into real world cases where the message IDs cannot just be split by commas? Or is this more of a theoretical concern?

**Comment by link2xt** [comment]
Mostly theoretical, so actually parsing all the cases specified in the standard is not necessary, but it would be nice to provide APIs for parsing even if they just split lists by spaces and wrap IDs into newtype. This way it will be possible to update all depending crates in the future if such a problem arises, for example if rust is used to parse NNTP archives.

**Comment by staktrace** [comment]
Ah, that sounds like a good idea indeed.
