### ISSUE TITLE
Join potential Mail Rust-Working group? 

### ISSUE THREAD

**Issue by hpk42** [staktrace/mailparse#54]
@staktrace As we are happily using mailparse from Delta Chat, and have just been invited to a potential new Rust WG on e-mail ... maybe you are also interested?  Here is the starting post 
https://internals.rust-lang.org/t/starting-a-rust-mail-wg/11678/2 with a github PR link in it. 

Feel free to close -- just didn't know how else to contact you easily. And maybe it's also interesting other others watching here.

**Comment by staktrace** [comment]
Thanks for the ping! I'll follow up on the internals thread.
