### ISSUE TITLE
Exclude < and > from message-IDs

### ISSUE THREAD

**Issue by link2xt** [staktrace/mailparse#56]
I had to exclude `<` and `>` after parsing in https://github.com/deltachat/deltachat-core-rust/pull/1306

Maybe change https://docs.rs/mailparse/0.11.0/mailparse/fn.msgidparse.html to exclude `<` and `>` from the message ID? It is just a separator, and adding it is easier than removing it for library users.

**Comment by alexwennerberg** [comment]
Hi -- I had a question about this issue @staktrace  -- my understanding is that the angle brackets *should* be considered part of the ID, per the RFCs (although I can't find the authoritative source). What is the reasoning behind stripping them?

**Comment by link2xt** [comment]
```
   Semantically, the angle bracket characters are not part of the
   msg-id; the msg-id is what is contained between the two angle bracket
   characters.
```

Source: https://datatracker.ietf.org/doc/html/rfc5322

**Comment by alexwennerberg** [comment]
Interesting, thank you!

**Comment by link2xt** [comment]
The real reason for this issue was that delta chat has been storing message-ids in the database without angle brackets even before it was ported to C. It's consistent, both contact addresses and message-IDs which are of the form `<foobar@example.com>` are stored in the database without angle brackets.
