### ISSUE TITLE
Return MailParseError from addrparse_header

### ISSUE THREAD

**Issue by link2xt** [staktrace/mailparse#57]
Currently (version 0.11.0) error type is `&'static str`. Why not `MailParseError`, like the rest of API?

**Comment by staktrace** [comment]
I guess when I first wrote `addrparse` I wasn't thinking of it as part of the main library but more of a standalone helper. So both `addrparse` and `msgidparse` produce `&str` as error values. I should revisit error propagation in general; even `get_key` and `get_value` never actually generate `MailParseError` results and can be updated. Will be a breaking API change though.

**Comment by link2xt** [comment]
Maybe switch to `anyhow` crate for error handling if you don't want users to match on error types.
