### ISSUE TITLE
Documentation: attachment example

### ISSUE THREAD

**Issue by benjaminweb** [staktrace/mailparse#59]
The Python library [imbox](https://github.com/martinrusev/imbox) has a straightforward example, including accessing attachments.

How can I access the attachments with mailparse?
I don't grasp it with its current documentation.

Related: https://github.com/jonhoo/rust-imap/issues/157

Would an umbrella module be required (using both `rust-imap` and `mailparse`) to resemble the functionality of imbox? Would [this](https://github.com/thomasfire/teleprint/blob/48570128f3b719f319f39c485ebca8ccd3d6990f/src/mailbot.rs#L140-L162) be a good starting point?

**Comment by staktrace** [comment]
You can do it with `mailparse`, but it's not as ergonomic as `imbox` because `mailparse` exposes slightly lower level APIs. You'd want to do something like:

```
for subpart in parsed.subparts {
  if subpart.get_content_disposition().disposition == DispositionType::Attachment {
    // it's an attachment
    let filename = subpart.get_content_disposition().params.get("filename");
    let file_data = subpart.get_body_raw()?;
    // do what you want with it
  }
}
```
