### ISSUE TITLE
cannot read html body of message with attachment(s)

### ISSUE THREAD

**Issue by benjaminweb** [staktrace/mailparse#60]
**REPRODUCE**

- html message
- with attachment(s)

**EXPECTED RESULT**
Inline
Ok("<html>…<html")

**ACTUAL RESULT**

Inline
Ok("")

---

- html body without attachments is correctly returned: Ok("<html>…<html")

**Comment by staktrace** [comment]
Please provide a compileable test case that demonstrates the problem. Your report is severely lacking in details and is basically unactionable.

**Comment by benjaminweb** [comment]
Is this actionable? https://github.com/staktrace/mailparse/issues/60

**Comment by staktrace** [comment]
Yes, this is actionable. The problem is that you're assuming the email subparts are linear. It's a nested structure.

So for the text part you want:

```
    assert_eq!(parsed.subparts[0].subparts[0].subparts[0].get_body().unwrap(), "foo_text\r\n");
```

and for the html part you want

```
        parsed.subparts[0].subparts[0].subparts[1].get_body().unwrap(),
```
but your HTML in that case is wrong anyway.

The PDF part is at
```
        parsed.subparts[1].get_body().unwrap(),
```

**Comment by staktrace** [comment]
In general if you want a part with a particular content type or disposition you should check the whole tree for that content type/disposition.

**Comment by benjaminweb** [comment]
That puts me back on track. Thank you!
