### ISSUE TITLE
Forced allocation in MailHeader

### ISSUE THREAD

**Issue by nabijaczleweli** [staktrace/mailparse#61]
The implementation of `MailHeader::get_key()` is as follows:
```rust
pub fn get_key(&self) -> String {
    decode_latin1(self.key).into_owned()
}
```

And `decode_latin1()` returns a `Cow<str>`, which, for the *vast* majority of header names will be the `Borrowed` variant.

My dataset is 850`000ish mails with on-average-5 headers, and that sounds like an easy optimisation.

I'd submit a patch, but a two-line PR is more annoying to merge than it's worth (and I'm not sure what your breakage policy is), to change the funxion to
```rust
pub fn get_key(&self) -> Cow<str> {
    decode_latin1(self.key)
}
```

However, exposing the `key` and `value` members would be just as if not *more* useful, and it doesn't break any interface.

**Comment by staktrace** [comment]
I'd accept a patch that adds a new method that returns the `Cow<str>` for the key. I don't want to change the existing signatures. And I don't plan on making the fields public unless you have a very compelling argument.

**Comment by nabijaczleweli** [comment]
Yeah, I don't really need the members themselves now, so I don't have a good argument (yet). Patch in #64
