### ISSUE TITLE
Parse comments in address lists

### ISSUE THREAD

**Issue by link2xt** [staktrace/mailparse#65]
There is a real use-case where parsing of comments is needed: https://github.com/deltachat/deltachat-core-rust/pull/1476#issuecomment-629681157

@staktrace You said comments are rare in practice, but now it happened: https://github.com/staktrace/mailparse/issues/53#issuecomment-575892915 I think it is [Postfix](http://www.postfix.org/) sending these mails with a comment.

**Comment by staktrace** [comment]
Ah, boo. I did actually add support for trailing comments but apparently only after bracketed addresses. In this case the address is not bracketed so the parsing is wrong. I'll see if I can fix it.

**Comment by r10s** [comment]
@staktrace thanks for fixing :)
