### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by hpk42** [staktrace/mailparse#66]
do you mind tagging a new release?  this way we could use it better from core-deltachat.

**Comment by staktrace** [comment]
Yup will do. I thought I left a comment on the other issue asking for confirmation that it fixed the problem for you but I guess I didn't hit submit or something... But since it seems like it does I'll push a new release either later today or tomorrow, when I'm back at my computer.

**Comment by staktrace** [comment]
Ok, I pushed 0.12.1 which has the fix.
