### ISSUE TITLE
Should mailparse try to handle malformed cases?

### ISSUE THREAD

**Issue by hugopeixoto** [staktrace/mailparse#68]
I downloaded my emails using the `imap` crate and passed them all through `mailparse`.

I had two failures, both from yahoo, when they acquired delicious. In both cases, the empty line between the headers and body was missing.

Should this be handled by `mailparse`? I'm not sure how common this is. In my case, it was 2 out of 150k emails, from the same sender.

**Comment by staktrace** [comment]
Normally I try to handle all kinds of malformed mail, but if we can't distinguish headers from body that seems like a really degenerate case that's practically impossible to handle. So in this case I'm going to punt and say no, not gonna handle it. But thank you for reporting this, it's good to know (also good to know that you had no problems parsing the rest of them).
