### ISSUE TITLE
Parse envelope header separately

### ISSUE THREAD

**Issue by Cerberuser** [staktrace/mailparse#69]
Do this crate expect the mail being parsed to have the "envelope header", as the email in `mbox` files do? If so, could it expose a new method of parsing it? For now, it parses the envelope as an ordinary header and so yields somewhat nonsensical results like this:
```
key == "From sender@domain.net Thu Aug 14 11"
value == "15:29 2003"
```

**Comment by staktrace** [comment]
No, this crate doesn't expect the mail to have that envelope header. The mbox file format is actually not specced anywhere, and would probably benefit from having a separate crate that parses it, and which delegates to `mailparse` to parse the actual mail part. This has come up before in https://github.com/staktrace/mailparse/issues/25, see that for some more context.

**Comment by Cerberuser** [comment]
Thanks, I'll look into it.
