### ISSUE TITLE
'Unexpected newline in header key'

### ISSUE THREAD

**Issue by vandenoever** [staktrace/mailparse#7]
A newline error is reported in a real-world email file.

Here is the relevant fragment:

[newline.txt](https://github.com/staktrace/mailparse/files/628941/newline.txt)

**Comment by staktrace** [comment]
Thanks for reporting this! I landed a commit that should fix this. I put your testcase in as a regression test as well. I'll push out a 0.5.0 version shortly which includes this fix and the other changes you submitted.

**Comment by staktrace** [comment]
Sorry, make that 0.4.1, since the changes are just bugfixes.

**Comment by vandenoever** [comment]
Very nice since I did not progress very far on fixing it. Reading your fix helps me understand the code.
