### ISSUE TITLE
msgidparse: assumes References are separated by whitespace, but it is optional

### ISSUE THREAD

**Issue by tommilligan** [staktrace/mailparse#72]
The current implementation splits ids within the `References` header on whitespace: https://github.com/staktrace/mailparse/blob/92ada51009052638d3e0f188219b89008ebe5208/src/msgidparse.rs#L56

However, [RFC5322 states](https://tools.ietf.org/html/rfc5322#section-3.6.4) (emphasis mine):
> The "References:" and "In-Reply-To:" fields each contain one or more unique message identifiers, **optionally** separated by CFWS [whitespace].

We're hitting this edge case in some emails pulled from an Exchange server.

I'd like to work on a solution to this initially, if that's okay.

---

Edit, for clarity, a failing test in `0.12.1` looks like:
```rust
        assert_eq!(
            msgidparse("<msg_one@foo.com><msg_two@bar.com>").unwrap(),
            MessageIdList(vec![
                "msg_one@foo.com".to_string(),
                "msg_two@bar.com".to_string(),
            ])
        );
```

**Comment by staktrace** [comment]
Feel free to work on a solution, thanks! The `msgidparse` is really just a bare-bones stub (as implied by the doc) and I'd be happy to accept PRs that flesh it out to handle more cases.
