### ISSUE TITLE
Allow recovery of raw headers

### ISSUE THREAD

**Issue by aredridel** [staktrace/mailparse#75]
I'd love to be able to use this library to parse, modify headers, and send onward messages.

Would you be open to a PR that adds `get_value_raw() -> &[u8]` to `MailHeader` ? I think that's sufficient for my case.

**Comment by staktrace** [comment]
I don't have objection to that in theory. You might have some trouble with the lifetime specifier, I don't think you can return a raw `&[u8]`. But you could clone it and return a `[u8]` and that would probably be ok.

**Comment by cybernoid** [comment]
I have a different request going in a similar direction: I have PGP signed messages where I want to verify the signature. Headers and body of a message or subpart are both signed with a single signature of course, so I need to retrieve the headers in raw form as well. Since the transfer encoding of the body still has to be undone (signing takes place before transfer encoding), I have to piece together the raw headers and the decoded body at some point anyway and I don't really care if it is done in mailparse or in my program.

Can we find a way to satisfy aredridel's and my request with a single modification?

**Comment by staktrace** [comment]
@cybernoid Hm, I'm not particularly familiar with PGP signing, and it's not clear to me from your comment how "raw" of the headers it is that you need. If you just need the raw byte data of the headers, you might be able to get a useful value by calling `parse_headers` and then taking the second value in the returned tuple (the `usize`) which is the byte index that divides the headers from the body. You can also then use `parse_mail` and the regular API to get the decoded body.

**Comment by aredridel** [comment]
I suspect full header recovery should be a different modification — but accessors to get that particular slice of the input would be delightful, IMO. I really like the design of mailparse being as copy-free as it is, only doing so when it needs to decode something. I think it's made the API useful while still being super low level. With a few more accessors — raw individual fields for me, for the whole header for you — it becomes a really solid foundation for being able to operate on messages and to handle modifications as exceptions carried with the higher layer. It would let an MTA do things like prepend a `Received:` header when sending it onward, while not copying anything needlessly. For my case, I can emit header by header, skipping the ones I intend to modify and emitting those from my layer; for the GPG case, you can read the whole header and body and just leverage the parsing code to make sure it's right.

**Comment by aredridel** [comment]
I've implemented a try at recovering the whole header section en masse in #77.

**Comment by staktrace** [comment]
@aredridel @cybernoid Take a look at the `headers` branch of this repo, I added some commits that add a `Headers` struct which exposes the raw bytes for the header block (in addition to implementing the `MailHeaderMap` trait). I think over time I can deprecate direct usage of `ParsedMail::headers` and migrate users to `ParsedMail::get_headers()` but for now this should address your use cases. Can you try it out and let me know if it doesn't work for you?

**Comment by aredridel** [comment]
Oh that's delightful. I'll have to try it tonight!

**Comment by aredridel** [comment]
Yeah, that's good for the gpg case, and random access — add IntoIter yielding MailHeader and it would work delightfully for me.

**Comment by staktrace** [comment]
Done!
