### ISSUE TITLE
Only the first mailbox in the list is decoded

### ISSUE THREAD

**Issue by link2xt** [staktrace/mailparse#79]
In the header `To: foo <foo@example.org>,=?UTF-8?B?Zm9v8J+Qm2Jhcg==?= <bar@example.org>` the second address is "foo🐛bar", and Thunderbird displays it correctly, but mailparse does not decode it.

A failing test is in #78

**Comment by staktrace** [comment]
Thanks for the PR with the failing test! I'll look into it soon.

**Comment by staktrace** [comment]
https://github.com/staktrace/mailparse/commit/b70236b71dd9885997cb5fe0962996802236c389 fixes one bug. But it doesn't fix this exact case, because detecting the encoded-word without the leading `=?` delimiter is not easy and not something I plan on doing. That's just a blatant spec violation.

**Comment by staktrace** [comment]
I'd be pretty shocked if Thunderbird parsed that correctly without the `=` since as far as I can tell it [requires the `=` char too](https://searchfox.org/comm-central/rev/193f6d3dfbac822d6395f8bb32edd60d664dfa84/mailnews/mime/jsmime/jsmime.js#533-537).

**Comment by link2xt** [comment]
I updated the first message, missing `=` is a typo a introduced while minimizing an example (it had around 20 email addresses in the `To` field).

**Comment by staktrace** [comment]
Ok great. This should be fixed by the above linked commit then.
