### ISSUE TITLE
[Question] comparison to rust-email

### ISSUE THREAD

**Issue by ngortheone** [staktrace/mailparse#80]
Hey @staktrace 

I've been playing with maildir crate, and it looks nice. Can you give some comments onto why write your own parsing email parsing library vs using https://github.com/niax/rust-email?
What are the pros/cons of this crate vs rust-email?

Thanks

**Comment by staktrace** [comment]
I've never used that crate so I can't do a comparison, sorry.

**Comment by hpk42** [comment]
@ngortheone conversely, i didn't know about rust-email so thanks for pointing it out. That being said, mailparse started in 2016 and rust-email in 2018 -- so your question is better asked with @niax :)  In any case, we are using mailparse for Delta Chat (a messenger-style e-mail client) for over a year and are *very* happy.  There are basically no known problems left even though Delta Chat processes e-mail from many different other e-mail clients and providers.  @stacktrace is doing an incredibly great job keeping mailparse focused and well maintained. So i am also using this post to express my/our gratitude :)

**Comment by ngortheone** [comment]
Thanks for your answers @staktrace @hpk42 !
