### ISSUE TITLE
Improperly decoded email message with `get_body` and `get_body_raw()

### ISSUE THREAD

**Issue by sakanouye** [staktrace/mailparse#84]
Hi @staktrace this is related to this [issue](https://stackoverflow.com/questions/48743636/binary-attachments-are-corrupted-when-using-mailparses-parsedmailget-body). However, I'm trying to decode this [email](https://gist.github.com/sakanouye/77b2db2c007b3d8721b471e0ad8d92c4) using this [application](https://github.com/sakanouye/privatemail/blob/sakanouye-patch-1/src/lib.rs#L172)

But it generates these weird characters in my email
<img width="713" alt="weird email" src="https://user-images.githubusercontent.com/30606862/113254839-f2f97700-927b-11eb-9dab-7f58dd52ead5.png">

Interesting both

```rs
let mail_content: String = parsed_mail.subparts[1].get_body().unwrap();
```

and 

```rs
let mail_content: String = parsed_mail.subparts[1]
        .get_body_raw()
        .unwrap()
        .iter()
        .map(|&x| x as u8)
        .map(|x| (x) as char)
        .collect();
```
doesn't seem to work here; I don't know if there's something I'm doing wrong with this API.

**Comment by staktrace** [comment]
I think you need to read up on the difference between bytes and chars (or equivalently, the difference between binary data and string data). The API is working as expected, but you're basically dumping binary data as a string so what you're seeing is necessarily going to be garbage.

**Comment by sakanouye** [comment]
@staktrace I find it difficult because the characters come not as bytes but string characters, the conversion is where I'm having issues. Any ideas?

**Comment by staktrace** [comment]
If the input mail data is coming in as a string then you need to fix that first. Without knowing the character encoding you can't just convert between bytes and chars. It's not really clear to me from your application code what you're trying to do. If you can make a standalone reduced example program that illustrates the problem that would be more useful.

**Comment by ch3ck** [comment]
Yes, will do

**Comment by sakanouye** [comment]
@staktrace sorry for the delay, here is a basic program that demonstrates what I was talking about: https://github.com/sakanouye/parse_mail

**Comment by staktrace** [comment]
Looking at that example it seems pretty clear that you're passing in something that `mailparse` is not intended to handle. What you have is some pre-parsed JSON encoding of an email, whereas per the `mailparse` README: `The library is designed to process real-world email data such as might be obtained by using the FETCH command on an IMAP server, or in a Maildir.` So I don't think `mailparse` is the right library for you. Sorry!
