### ISSUE TITLE
Unexpected newline in header key

### ISSUE THREAD

**Issue by Necronian** [staktrace/mailparse#85]
Out of ~60k of the emails I just parsed 2 give me an Unexpected newline in header key error.

Here is the contents of one of the messages;
```
Delivered-To: linphone@example.com
Received: by 10.220.167.194 with SMTP id r2cs51443vcy;
        Wed, 4 May 2011 09:12:05 -0700 (PDT)
Received: by 10.227.176.135 with SMTP id be7mr1394123wbb.0.1304525525196;
        Wed, 04 May 2011 09:12:05 -0700 (PDT)
Return-Path: <www-data@linphone.org>
Received: from linphone.org (linphone.org [91.121.196.132])
        by mx.google.com with ESMTPS id v18si1163679wbb.35.2011.05.04.09.12.03
        (version=TLSv1/SSLv3 cipher=OTHER);
        Wed, 04 May 2011 09:12:04 -0700 (PDT)
Received-SPF: pass (google.com: domain of www-data@linphone.org designates 91.121.196.132 as permitted sender) client-ip=91.121.196.132;
Authentication-Results: mx.google.com; spf=pass (google.com: domain of www-data@linphone.org designates 91.121.196.132 as permitted sender) smtp.mail=www-data@linphone.org
Received: by linphone.org (Postfix, from userid 33)
	id 0B2D41FFF3; Wed,  4 May 2011 18:12:02 +0200 (CEST)
To: linphone@example.com
Subject: Start your sip.linphone.org service
Reply-to: No reply @ Linphone.org <no.reply@linphone.org>
From: No reply @ Linphone.org <no.reply@linphone.org>
X-Sender: <www.linphone.org>
X-Mailer: PHP
X-auth-smtp-user: No reply @ Linphone.org <no.reply@linphone.org> 
X-abuse-contact: No reply @ Linphone.org <no.reply@linphone.org> 
Date: Wed, 4 May 2011 18:12:02 +0200
MIME-Version: 1.0
Content-Type: multipart/alternative; boundary="_----------=_parties_de3c0f96a0b7e75e3122b92462fd869c"
Message-Id: <20110504161203.0B2D41FFF3@linphone.org>
Content-Length: 1161
X-TUID: L598s4TdSAFL

--_----------=_parties_de3c0f96a0b7e75e3122b92462fd869c
Content-Type: text/plain
charset="utf-8"
Content-Transfer-Encoding: 8bit

Hello,

activation pending for using your Linphone account.

Please use the link bellow to activate your account :


http://www.linphone.org/eng/linphone/register-a-linphone-account.html?action=confirm&confirmation_key=


Regards,
 
The Linphone team.


--_----------=_parties_de3c0f96a0b7e75e3122b92462fd869c
Content-Type: text/html; charset="utf-8"; Content-Transfer-Encoding: 8bit;

<html>
	<head>
	  <title>Start your sip.linphone.org service</title>
	</head>
	<body>
          <p>Hello,</p>
	  <p>activation pending for using your Linphone account.<br />
	  Please use the link bellow to activate your account :</p>
	  <p><a href="http://www.linphone.org/eng/linphone/register-a-linphone-account.html?action=confirm&confirmation_key=">http://www.linphone.org/eng/linphone/register-a-linphone-account.html?action=confirm&confirmation_key=</a></p>
	  <p>&nbsp;</p>
	  <p>Regards,<br /> 
	  The Linphone team.</p>
	</body>
	</html>
--_----------=_parties_de3c0f96a0b7e75e3122b92462fd869c--
```

**Comment by staktrace** [comment]
This part:

```
Content-Type: text/plain
charset="utf-8"
Content-Transfer-Encoding: 8bit
```

is indeed invalid. It should instead look like this:

```
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 8bit
```

which is why mailparse is complaining. Incidentally the other part of the multipart message also has errors:

```
Content-Type: text/html; charset="utf-8"; Content-Transfer-Encoding: 8bit;
```

should be

```
Content-Type: text/html; charset="utf-8"
Content-Transfer-Encoding: 8bit
```

How did you get this mail file? I'm wondering if some other MTA/MUA earlier in the process mangled it.

**Comment by Necronian** [comment]
Well as you can see it's a decade old email so I can't 100% guarantee the providence. The mail was downloaded to my local mail directory using mbsync from my Fastmail email account. Based on the dates I may have used Fastmail's email migration tools when I first signed up? Or possibly I uploaded it myself using mbsync or offlineimap? Either is possible.

But out of all of my emails there are only two that have that error. Both sent the same day from the same origin with the same problem and are the only emails I have received from that sender.

**Comment by staktrace** [comment]
Hm, thanks for the info. As it stands I don't think I really want to try to handle this kind of error in mailparse. If you still have this email in fastmail I'd be interested in knowing if they handle it as expected, or if their view of the raw email looks different. But if you don't care to pursue this further then that's fine too.

**Comment by Necronian** [comment]
> I don't think I really want to try to handle this kind of error in mailparse. 

Seems reasonable. A lot of work for little reward.

As far as I can see in Fastmail the email is displayed no different than any other. Since I'm using your library in my notmuch tagging program I took a look at notmuch's output and it seems to handle it okay. Neomutt on the other hand doesn't like it. The Content-Transfer-Encoding: 8bit ends up displayed in the message body.

**Comment by staktrace** [comment]
I spent some more time looking at this today and decided it was probably worth handling after all. It's not spec-compliant but obviously occurs in the wild, and other MTA/MUAs seems to handle it somewhat gracefully, so why not. It's unlikely that anybody is relying on the current behaviour in this case.
