### ISSUE TITLE
unexpected prefix "\r\n " in MailHeader's value field when MIME header separated by ":\r\n"

### ISSUE THREAD

**Issue by qsdgy** [staktrace/mailparse#91]
e.g.,

```rust
"X-MS-Exchange-Transport-CrossTenantHeadersStripped:\r\n HK2APC01FT019.eop-APC01.prod.protection.outlook.com\r\n"
```

shows like:
```rust
"X-MS-Exchange-Transport-CrossTenantHeadersStripped:
 HK2APC01FT019.eop-APC01.prod.protection.outlook.com
"
```

would be parsed to

```rust

MailHeader {
    key: "X-MS-Exchange-Transport-CrossTenantHeadersStripped",
    value: "\r\n HK2APC01FT019.eop-APC01.prod.protection.outlook.com\r",
}

```

**Comment by staktrace** [comment]
Same as #90, if you use `.get_value()` on the MailHeader object you should get the right value with the `\r\n` characters removed.

**Comment by qsdgy** [comment]
MIME header value may be multi-line string separated by `"\r\n "`, well-handled by `MailHeader::get_value()`, taking `&[u8]` from `MailHeader::get_value_raw()` may need to handle delimiter `"\r\n "`, leading `"\r\n "` and trailing `"\r"` in slice.
