### ISSUE TITLE
Owned alternative to `ParsedMail` type

### ISSUE THREAD

**Issue by link2xt** [staktrace/mailparse#97]
It is sometimes useful to pass both the underlying `Vec<u8>` and `ParsedMail` pointing into it around. But if you pass `Vec<u8>` and a separate `ParsedMail<'a>` argument, it is impossible to specify that 'a points into the `Vec` to pass the borrow checker.

For this use case it would be nice to have an `OwnedParsedMail` type, similar to
```
use ouroboros::self_referencing;

/// Parsed mail that owns the underlying raw bytes. 
#[self_referencing]
pub struct OwnedParsedMail {    
    /// Raw content that is parsed.
    pub raw: Vec<u8>,                                                             
                      
    /// Parsed whole or part of the `raw` message.  
    #[borrows(raw)]
    pub mail: ParsedMail<'this>,                             
}  
```
(using [ouroboros](https://crates.io/crates/ouroboros) crate).

It will then be possible to implement `Cow` for `ParsedMail`, so `.to_owned()` returns an `OwnedParsedMail`.

**Comment by staktrace** [comment]
Interesting, I didn't know about this crate! Just for my understanding - you should be able to create this self-referencing struct in the caller code too, right? It's probably more convenient for reuse if it lives in `mailparse` though. If we put it in `mailparse` I'd want it behind a disabled-by-default feature flag, I think

**Comment by link2xt** [comment]
> Interesting, I didn't know about this crate! Just for my understanding - you should be able to create this self-referencing struct in the caller code too, right?

Self-referencing struct and `ouroboros` crate are just an implementation detail.

What I want is an `OwnedParsedMail` that is to `ParsedMail` what a `String` is to `str`. It should probably have a constructor `OwnedParsedMail::from()` that takes a `Vec<u8>` to construct it and `AsRef<ParsedMail>` implementation to get the `ParsedMail` from it. No need to expose the internals and references to ourobors crate.

> It's probably more convenient for reuse if it lives in mailparse though.

Sure, this type will share a lot of implementation details, and `ParsedMail` needs to implement traits like [ToOwned](https://doc.rust-lang.org/std/borrow/trait.ToOwned.html) that have `ToOwned::Owned = OwnedParsedMail`.

> If we put it in mailparse I'd want it behind a disabled-by-default feature flag, I think

I am not fan of feature flags, think they are a mistake in Rust design. Conditional compilation is like an `#ifdef` in C world, it usually can be avoided by splitting the feature into a separate crate instead. Like putting internals into a `mailparse_inner` crate, `ParsedMail` public interface into `mailparse` crate, and this new feature into `mailparse_owned` crate, something like this. Or just put everything into one crate and rely on dead code elimination to remove unused structures, at the cost of increased compilation times.

The problem with feature flags is that any dependency can enable the feature flag for some crate and then this feature is enabled for all other users of this create in your program. Like `regex` crate has features that result in faster matching at the cost of higher regex compilation times. You disable this feature to have lower latency, benchmark it, then pull in a dependency that enables this feature and suddenly your regexps compile slower.

I'd just put this new type inside the `mailparse` crate without any feature flags.

**Comment by link2xt** [comment]
Overall this is just an idea, not really important to have it now. I opened it only because I had to reparse the mail part twice in the code, which could have been avoided if there was an easy way to pass the parse tree along with the underlying `Vec<u8>` without introducing `'a` lifetimes all over the application code. Parsing is probably fast compared to decrypting and database operations on disk, so it's unlikely to cause us performance issues.

Feel free to just stamp a "good first issue" on it if you want :)

**Comment by staktrace** [comment]
Thanks. I gave this some thought, and [added an example](https://github.com/staktrace/mailparse/commit/ea01dca6221c104a51ea4adc6fd50fb1a252b7f3) to the `examples/` folder that shows how to use ouroboros to create an OwnedMail type like in your example. However at the moment I don't feel that this needs to be added to the crate itself; I prefer keeping it as lightweight as possible. Consumers of the library who need to have an owned version can do the wrapping themselves.
