### ISSUE TITLE
Parsing "Received" header

### ISSUE THREAD

**Issue by alexwennerberg** [staktrace/mailparse#99]
Hi, I'm trying to use this library to parse the date from the "Received" header. 

It seems, from RFC2822, that this header has a specific syntax: https://datatracker.ietf.org/doc/html/rfc2822.html#section-3.6.7 somewhat similar to the Content-Disposition header

How would you feel about me creating a PR for a "parse_received" function? Or a "parse_trace_field" function with an enum for the two types specified in the RFC

**Comment by staktrace** [comment]
That sounds fine. In terms of the public api I'd prefer separate `parse_received` and `parse_return_path` functions that can share an implementation by delegating to a helper.

**Comment by alexwennerberg** [comment]
Great, I’ll put together something if i have a chance over my winter break

Alex

**Comment by staktrace** [comment]
@alexwennerberg any progress here?

**Comment by alexwennerberg** [comment]
I haven't gotten a chance yet -- I put together a workaround for my use case. I will let you know if I get a chance

**Comment by staktrace** [comment]
Ok I'll close this for now, feel free to reopen.
